# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\Ethan\Documents\GitHub\Statistics_Calculator_MK1\main_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(411, 527)
        self.groupBox_selectedColor = QtWidgets.QGroupBox(Form)
        self.groupBox_selectedColor.setGeometry(QtCore.QRect(70, 50, 271, 361))
        self.groupBox_selectedColor.setObjectName("groupBox_selectedColor")
        self.pushButton_colorsAll = QtWidgets.QPushButton(self.groupBox_selectedColor)
        self.pushButton_colorsAll.setGeometry(QtCore.QRect(10, 170, 71, 23))
        self.pushButton_colorsAll.setObjectName("pushButton_colorsAll")
        self.widget_colorPanel = QtWidgets.QWidget(self.groupBox_selectedColor)
        self.widget_colorPanel.setGeometry(QtCore.QRect(10, 140, 234, 23))
        self.widget_colorPanel.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.widget_colorPanel.setObjectName("widget_colorPanel")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget_colorPanel)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.image_colorPanel = QtWidgets.QLabel(self.groupBox_selectedColor)
        self.image_colorPanel.setGeometry(QtCore.QRect(10, 20, 234, 120))
        self.image_colorPanel.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.image_colorPanel.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.image_colorPanel.setText("")
        self.image_colorPanel.setPixmap(QtGui.QPixmap(":/images/res/colors.png"))
        self.image_colorPanel.setObjectName("image_colorPanel")
        self.pushButton_colorsInvert = QtWidgets.QPushButton(self.groupBox_selectedColor)
        self.pushButton_colorsInvert.setGeometry(QtCore.QRect(90, 170, 71, 23))
        self.pushButton_colorsInvert.setObjectName("pushButton_colorsInvert")
        self.label_colorPanelPrimaryRemap = QtWidgets.QLabel(self.groupBox_selectedColor)
        self.label_colorPanelPrimaryRemap.setGeometry(QtCore.QRect(250, 20, 13, 120))
        self.label_colorPanelPrimaryRemap.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_colorPanelPrimaryRemap.setText("")
        self.label_colorPanelPrimaryRemap.setPixmap(QtGui.QPixmap(":/images/res/remap.png"))
        self.label_colorPanelPrimaryRemap.setObjectName("label_colorPanelPrimaryRemap")
        self.checkBox_primaryRemap = QtWidgets.QCheckBox(self.groupBox_selectedColor)
        self.checkBox_primaryRemap.setGeometry(QtCore.QRect(250, 144, 16, 16))
        self.checkBox_primaryRemap.setText("")
        self.checkBox_primaryRemap.setObjectName("checkBox_primaryRemap")
        self.pushButton_deleteColor = QtWidgets.QPushButton(self.groupBox_selectedColor)
        self.pushButton_deleteColor.setGeometry(QtCore.QRect(10, 270, 71, 23))
        self.pushButton_deleteColor.setObjectName("pushButton_deleteColor")
        self.comboBox_remapToColor = QtWidgets.QComboBox(self.groupBox_selectedColor)
        self.comboBox_remapToColor.setGeometry(QtCore.QRect(90, 210, 91, 22))
        self.comboBox_remapToColor.setObjectName("comboBox_remapToColor")
        self.pushButton_remapTo = QtWidgets.QPushButton(self.groupBox_selectedColor)
        self.pushButton_remapTo.setGeometry(QtCore.QRect(10, 210, 71, 23))
        self.pushButton_remapTo.setObjectName("pushButton_remapTo")
        self.pushButton_incrBrightness = QtWidgets.QPushButton(self.groupBox_selectedColor)
        self.pushButton_incrBrightness.setGeometry(QtCore.QRect(10, 240, 71, 23))
        self.pushButton_incrBrightness.setObjectName("pushButton_incrBrightness")
        self.pushButton_decrBrightness = QtWidgets.QPushButton(self.groupBox_selectedColor)
        self.pushButton_decrBrightness.setGeometry(QtCore.QRect(90, 240, 71, 23))
        self.pushButton_decrBrightness.setObjectName("pushButton_decrBrightness")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.groupBox_selectedColor.setTitle(_translate("Form", "Color Manipulations"))
        self.pushButton_colorsAll.setText(_translate("Form", "All Colors"))
        self.pushButton_colorsInvert.setText(_translate("Form", "Invert"))
        self.pushButton_deleteColor.setText(_translate("Form", "Delete"))
        self.pushButton_remapTo.setText(_translate("Form", "Remap to"))
        self.pushButton_incrBrightness.setText(_translate("Form", "+ Brightness"))
        self.pushButton_decrBrightness.setText(_translate("Form", "- Brightness"))
